language: python
python: 3.7
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f envs/dev.yml
  - source activate ttt
  - pip install codecov
  - python setup.py install
before_script:
  - flake8
script:
  - pytest
  - pytest --cov=ttt tests/
  - pytest -v --cov-report xml --cov=ttt tests
  - py.test -v --cov-config .coveragerc --cov=ttt tests
  - coverage
  - coverage report --show-missing
after_success:
  - coverage
  - coveralls
  - codecov